mirit/mirit/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('note.urls', namespace='notes')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

mirit/note/urls.py
from django.urls import path

from .views import *

app_name = 'notes'

urlpatterns = [
    path('', PostListView.as_view(), name='index'),
    path('profile/<int:pk>/', ProfileDetailView.as_view(), name='profile'),
    path('note/<int:pk>/', PostDetailView.as_view(), name='note_detail'),
    path('create/', PostCreateView.as_view(), name='note_create'),
    path('note/<int:pk>/edit/', PostUpdateView.as_view(), name='note_edit'),
    path('note/stat', PostStatView.as_view(), name='note_stat'),
    path('createmany/', CreateMany.as_view(), name='create_many'),
    path('many/', ManyView.as_view(), name='many'),
    
]

mirit/note/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


ADMIN = 'admin'
MODERATOR = 'moderator'
USER = 'user'

CHOICES = (
    (ADMIN, ADMIN),
    (MODERATOR, MODERATOR),
    (USER, USER),
)


class User(AbstractUser):

    fio = models.TextField(
        verbose_name='ФИО'
    )
    birth_date = models.DateField(
        verbose_name='Дата рождения',
        null=True,
        blank=True
    )
    srole = models.CharField(
        'Статус пользователя',
        max_length=20,
        choices=CHOICES,
        default=USER
    )

    @property
    def is_admin(self):
        return (
            self.role == ADMIN or self.is_staff
            or self.is_superuser
        )

    @property
    def is_moderator(self):
        return self.role == MODERATOR

    class Meta:
        ordering = ('-id',)
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.username


class Note(models.Model):
    title = models.CharField(
        max_length=255,
        verbose_name='Заголовок заметки'
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    text = models.TextField(
        verbose_name='Текст заметки'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='pub_author',
        verbose_name='Автор заметки'
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Заметка'
        verbose_name_plural = 'Заметки'

    def get_absolute_url(self):
        return reverse('notes:note_detail', args=[self.id])

    def __str__(self):
        return self.text[:15]
        


class ManyPole(models.Model):
    photo = models.ImageField(upload_to='many_test', null=True)
    # many = models.ForeignKey('ManyToManyTest', on_delete=models.CASCADE, related_name='many_pole')


class ManyToManyTest(models.Model):
    YESNO = (
        ('ДА', 'ДА'),
        ('НЕТ', 'НЕТ')
    )
    user = models.ForeignKey(User, related_name='author', on_delete=models.CASCADE)
    pole = models.CharField(verbose_name='Вопрос', choices=YESNO, max_length=3)
    pole_photo = models.ManyToManyField(ManyPole, related_name='photo_1')

    def get_absolute_url(self):
        return reverse('notes:index')

mirit/note/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Note, ManyToManyTest, ManyPole


class NoteForm(forms.ModelForm):

    class Meta:

        model = Note
        fields = ('title', 'text')
        labels = {
            'title': _('Заголовок заметки'),
            'text': _('Текст заметки'),
        }
        help_texts = {
            'title': _('Здесь текст заголовка для фашей заметки'),
            'text': _('Здесь текст вашей заметки'),
        }

        def clean_text(self):
            text = self.cleaned_data['text']

            if text == '':
                raise forms.ValidatorError(
                    'В заметке обязательно должен быть текст'
                )
            return text


class ManyForm(forms.ModelForm):

    class Meta:

        model = ManyToManyTest
        fields = ('pole',)
        widgets = {
            'pole': forms.RadioSelect(),
            # 'pole_photo': forms.ClearableFileInput(attrs={'multiple': True, 'required': False})
        }


# class PhotoFileForm(forms.Form):
#     photo = forms.FileField(widget=forms.ClearableFileInput(
#         attrs={'multiple': True, 'required': False}))

class PhotoFileForm(forms.ModelForm):
    photo = forms.ImageField(
        widget=forms.ClearableFileInput(attrs={'multiple': True, 'required': False})
    )
    class Meta:
        model = ManyPole
        fields = ('photo',)

mirit/note/views.py
from xml.dom import ValidationErr
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponseRedirect
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    FormView,
)
from datetime import date, datetime

from .forms import NoteForm, ManyForm, PhotoFileForm
from .models import Note, User, ManyPole, ManyToManyTest


class PostListView(ListView):
    model = Note
    template_name = 'note/index.html'
    paginate_by = 20


class PostDetailView(DetailView):
    model = Note
    template_name = 'note/post_detail.html'


class ProfileDetailView(ListView):
    model = Note
    template_name = 'note/profile.html'
    paginate_by = 20

    def get_queryset(self):
        username = self.kwargs.get('pk')
        author = get_object_or_404(User, pk=username)
        q = author.pub_author.all()
        return q


class PostCreateView(CreateView):
    template_name = 'note/create_post.html'
    form_class = NoteForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class PostUpdateView(UpdateView):
    model = Note
    template_name = 'note/create_post.html'
    form_class = NoteForm


class PostStatView(ListView):
    model = Note
    paginate_by = 10
    template_name = 'note/stat.html'

    def get_queryset(self):
        def_val = datetime.now()
        start_date = self.request.GET.get('start', def_val)
        end_date = self.request.GET.get('end', def_val)
        new_context = Note.objects.filter(pub_date__gte=start_date, pub_date__lte=end_date)
        return new_context

    def get_context_data(self, **kwargs):
        def_val = datetime.now()
        context = super(PostStatView, self).get_context_data(**kwargs)
        context['start'] = self.request.GET.get('start', def_val)
        context['end'] = self.request.GET.get('end', def_val)
        context['count'] = Note.objects.all()
        return context


class CreateMany(FormView):
    template_name = 'note/many.html'
    form_photo = PhotoFileForm
    form_quest = ManyForm

    def get_success_url(self):
        return reverse ('notes:many')

    def get(self, request, *args, **kwargs):
        context = {'form_quest': self.form_quest, 'form_photo': self.form_photo}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        self.object = None
        form_quest = ManyForm(request.POST or None, request.FILES or None)
        form_photo = PhotoFileForm(request.POST or None, request.FILES or None)
        files = request.FILES.getlist('photo')
        if form_quest.is_valid() and form_photo.is_valid():
            f_q = form_quest.save(commit=False)
            f_q.user = self.request.user
            f_q.save()
            for f in files:
                f_p = ManyPole(photo=f)
                f_p.save()
                f_q.pole_photo.add(f_p.id)           
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.form_invalid(form_quest)


class ManyView(ListView):
    model = ManyToManyTest
    template_name = 'note/many_list.html'

mirit/templates/note/create_post.html
{% extends 'base.html' %}
{% block title %}
{% if is_edit %} 
Редактировать запись
{% else %}
Добавить запись
{% endif %} 
{% endblock %}
{% block content %}
  <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                Новый пост             
              </div>
              <div class="card-body">        
                <form method="post" action="{% if is_edit %} {% url 'notes:note_edit' post_id %} {% else %} {% url 'notes:note_create' %} {% endif %}" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group row my-3 p-3">
                  <label for="id_text">
                    Заголовок заметки                 
                    <span class="required text-danger" >*</span>                  
                  </label>
                   {{ form.title }}              
                 
                </div>  
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст заметки                 
                      <span class="required text-danger" >*</span>                  
                    </label>
                     {{ form.text }}              
                    <small id="id_text-help" class="form-text text-muted">
                      Ваш текст
                    </small>                  
                  </div>            
                  <div class="d-flex justify-content-end">
                  
               <button type="submit" class="btn btn-primary" name='send'>
              {% if is_edit %}
               Сохранить
              {% else %}
                Добавить
             {% endif %}
            </button>
            </form>
  {% endblock %}    

mirit/templates/note/index.html
{% extends 'base.html' %}
{% block title %}Последние заметки{% endblock %}
{% block content %}

  <div class="container py-5">

  {% for post in object_list %}
      <ul>
      <li>
        Автор: {{ post.author.fio }}<br>
        <a href="{% url 'notes:profile' post.author.pk %}">все посты пользователя</a>
      </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>{{ post.text }}</p>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}

  {% include 'note/includes/paginator.html' %}
  </div>
{% endblock %}    

mirit/templates/note/many.html
{% extends 'base.html' %}

{% block content %}
<form method="post" action="{% url 'notes:create_many' %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form_quest.pole }}
    {% csrf_token %}
    {{ form_photo.photo }}
    <button type="submit" class="btn btn-primary" name='send'>Сохранить</button>
</form>
{% endblock %}

mirit/templates/note/many_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}
{% block title %}Последние заметки{% endblock %}
{% block content %}
    {% for post in object_list %}
        {{ post.user }}
        {{ post.pole }}
        {% for item in post.pole_photo.all %}
            {% thumbnail item.photo "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
        {% endfor %}    
        
        
    {% endfor %}
{% endblock %}

mirit/templates/note/post_detail.html
{% extends 'base.html' %}
{% block title %}Пост {{ post.text|truncatechars:30 }}{% endblock %}
{% block content %}

  
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ object.pub_date|date:"d E Y" }}  
            </li>
              <li class="list-group-item">
                Автор: {{ object.author.fio }}</a> 
              </li>
              </ul>
        </aside>
        <article class="col-12 col-md-8">
          <p>
           {{ object.text}}
          </p>
          {% if user == object.author %}
          <p>
          <a href="{% url 'notes:note_edit' object.pk %}">
            Редактировать запись
            </a>
          </p>
          {% endif %}
          
          </article>
      </div> 
  
  {% include 'note/includes/paginator.html' %}
{% endblock %}

mirit/templates/note/profile.html
{% extends 'base.html' %}
{% block title %}Профайл пользователя 
{{ author.fio }}
{% endblock %}
{% block content %}

{% for post in object_list %}
{% if forloop.first %}

    <div class="container py-5">        
        <h1>Все посты пользователя {{ post.author.fio }} </h1>
        <h3>Всего постов: {{ object_list|length }}</h3>
        <article>
          <ul>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>
          </ul>
          <p>
          {{ post.text }}
          </p>
          <a href="{% url 'notes:note_detail' post.pk %}">подробная информация </a>
        </article>       
                
        {% else %}
        <ul>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }} 
          </li>
        </ul>
        <p>
        {{ post.text }}
        </p>
        <a href="{% url 'notes:note_detail' post.pk %}">подробная информация </a>

        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% include 'note/includes/paginator.html' %} 
      </div>
       
{% endblock %} 

mirit/templates/note/stat.html
{% extends 'base.html' %}
{% block title %}Последние заметки{% endblock %}
{% block content %}
<div class="container py-5">
    <form method="get" action="{% url 'notes:note_stat' %}">
        <p>ОТ: <input type="datetime-local" value={{start}} name="start" required></p>
        <p>ДО: <input type="datetime-local" value={{end}} name="end" required></p>
        <p><input type="submit" name="submit" value="submit"/></p>
    </form>
    <input type="checkbox" id="one" onchange="fun1()">
</div>
<div class="container py-5">
    Общее воличество постов: {{ count|length }}
</div>
<script>
function fun1() {
var chbox;
chbox=document.getElementById('one');
  if (chbox.checked) {
    window.location.href = 'notes:note_stat';
  }
  else {
    window.location.href = '/';
  }
}
</script>
  <div class="container py-5">
  
  {% for post in object_list %}
      <ul>
      <li>
        Автор: {{ post.author.fio }}<br>
        <a href="{% url 'notes:profile' post.author.pk %}">все посты пользователя</a>
      </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>{{ post.text }}</p>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}

  {% include 'note/includes/paginator.html' %}
  </div>

{% endblock %}    