mirit/mirit/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('note.urls', namespace='notes')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

mirit/note/urls.py
from django.urls import path

from .views import *

app_name = 'notes'

urlpatterns = [
    path('', PostListView.as_view(), name='index'),
    path('profile/<int:pk>/', ProfileDetailView.as_view(), name='profile'),
    path('note/<int:pk>/', PostDetailView.as_view(), name='note_detail'),
    path('create/', PostCreateView.as_view(), name='note_create'),
    path('note/<int:pk>/edit/', PostUpdateView.as_view(), name='note_edit'),
    path('note/stat', PostStatView.as_view(), name='note_stat'),
    path('createmany/', CreateMany.as_view(), name='create_many'),
    path('many/', ManyView.as_view(), name='many'),
    
]

mirit/templates/includes/footer.html
{% load static %}
<p>© {{ year }} Copyright <span style="color:red">Ми</span>рит</p>

mirit/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
        <a class="navbar-brand" href="{% url 'notes:index' %}">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ми</span>рит
        </a>
    {% with request.resolver_match.view_name as view_name %}
     <ul class="nav nav-pills">
        <li class="nav-item"> 
          <a class="nav-link
          {% if view_name  == '' %}
            active
          {% endif %}"
          href="{% url 'notes:note_stat' %}">
          сортировка
          </a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link
          {% if view_name  == '' %}
            active
          {% endif %}"
          href="{% url 'notes:many' %}">
          Проверка мэни
          </a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item"> 
          <a class="nav-link
          {% if view_name  == '' %}
            active
          {% endif %}"
          href="{% url 'notes:note_create' %}">
          Новая запись
          </a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link
          {% if view_name  == '' %}
            active
          {% endif %}"
          href="{% url 'notes:create_many' %}">
          Мэни ту мэни поле
          </a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light
          {% if view_name  == 'users:logout' %}
            active
          {% endif %}"
          href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li>
          Пользователь: {{ user.fio }}
        <li>
        {% else %}
        <li class="nav-item"> 
          <a class="nav-link link-light
          {% if view_name  == 'users:login' %}
            active
          {% endif %}"
          href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light
          {% if view_name  == 'users:signup' %}
            active
          {% endif %}"
          href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
      </ul>   
    </div>
</nav>  
{% endwith %}    